import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{McpTools}from'../src/mcp-tools.js';
test('development HTTP routes are registered',async()=>{const src=await readFile(new URL('../src/development-api.ts',import.meta.url),'utf8');for(const route of['/api/development/sessions','/api/development/start','/api/development/context','/api/development/kpis','/api/development/snapshot','/api/development/divergence'])assert.ok(src.includes(route));});
test('development MCP tools are exposed',()=>{for(const name of['development_session_open','development_start','development_context_get','project_snapshot_get','project_snapshot_publish','development_divergence_check'])assert.ok(name in McpTools);});
test('HTTP development context is compact and slightly broader for cross-project learning',async()=>{const src=await readFile(new URL('../src/development-api.ts',import.meta.url),'utf8');assert.match(src,/max\(5\)/);assert.match(src,/default\(3\)/);assert.match(src,/default\(5000\)/);assert.match(src,/minConfidence:\.35/);assert.match(src,/truncated/);assert.match(src,/knowledgeType/);assert.match(src,/productionUsable/);});
test('MCP development context matches cross-project retrieval defaults',async()=>{const src=await readFile(new URL('../src/mcp-server.ts',import.meta.url),'utf8');assert.match(src,/Math\.min\(input\.limit\?\?3,5\)/);assert.match(src,/maxChars=5000/);assert.match(src,/input\.maxChars\?\?5000/);assert.match(src,/minConfidence:\.35/);assert.match(src,/knowledgeType/);assert.match(src,/productionUsable/);assert.match(src,/returnedChars/);});
test('HTTP cache requires repository and shared knowledge to be unchanged',async()=>{const http=await readFile(new URL('../src/development-api.ts',import.meta.url),'utf8');assert.match(http,/repository_and_knowledge_unchanged/);assert.match(http,/shared_knowledge_changed/);assert.match(http,/latestKnowledgeRevision/);assert.match(http,/head_commit===headCommit/);assert.match(http,/returnedItems:0/);});
test('MCP cache also requires repository and shared knowledge to be unchanged',async()=>{const mcp=await readFile(new URL('../src/mcp-server.ts',import.meta.url),'utf8');assert.match(mcp,/repository_and_knowledge_unchanged/);assert.match(mcp,/shared_knowledge_changed/);assert.match(mcp,/latestKnowledgeRevision/);assert.match(mcp,/head_commit===headCommit/);assert.match(mcp,/returnedItems:0/);});
test('development start supports application and component identity',()=>{const parsed=McpTools.development_start.parse({workspaceId:'w',projectId:'p',appId:'numeria-studio',componentId:'web',agentId:'a',clientType:'chatgpt',repository:'owner/repo',query:'管理者権限'});assert.equal(parsed.appId,'numeria-studio');assert.equal(parsed.componentId,'web');assert.equal(parsed.limit,3);assert.equal(parsed.maxChars,5000);});
test('development context cache can be explicitly bypassed',()=>{const parsed=McpTools.development_context_get.parse({workspaceId:'w',projectId:'p',query:'q',headCommit:'abc'});assert.equal(parsed.forceRefresh,false);assert.equal(parsed.headCommit,'abc');});
