import test from'node:test';import assert from'node:assert/strict';import{buildServer}from'../src/server.js';
const db=process.env.DATABASE_URL;
test('HTTP development hub supports compact token-first context and cache',{skip:!db},async()=>{const app=await buildServer();try{const suffix=Date.now().toString(36),workspaceId=`route_e2e_${suffix}`,projectId='shared-app';const opened=await app.inject({method:'POST',url:'/api/development/sessions',payload:{workspaceId,projectId,agentId:'agent-a',clientType:'chatgpt',repository:'owner/shared-app',baseCommit:'abc',currentTask:'route e2e'}});assert.equal(opened.statusCode,201);const sessionId=opened.json().session.id;const context=await app.inject({method:'POST',url:'/api/development/context',payload:{workspaceId,projectId,query:'typecheck structural failures'}});assert.equal(context.statusCode,200);for(const item of context.json().intelligence){assert.deepEqual(Object.keys(item).sort(),['confidence','id','summary','title']);}const snapshot=await app.inject({method:'PUT',url:'/api/development/snapshot',payload:{workspaceId,projectId,sessionId,repository:'owner/shared-app',expectedVersion:undefined,currentTask:'route e2e',headCommit:'abc'}});assert.equal(snapshot.statusCode,200);assert.equal(Number(snapshot.json().snapshot.version),1);const cached=await app.inject({method:'POST',url:'/api/development/context',payload:{workspaceId,projectId,query:'typecheck structural failures',headCommit:'abc'}});assert.equal(cached.statusCode,200);assert.equal(cached.json().cache.hit,true);assert.equal(cached.json().intelligence.length,0);assert.ok(cached.json().snapshotRef);assert.equal(cached.json().snapshot,undefined);const kpis=await app.inject({method:'GET',url:`/api/development/kpis?workspaceId=${encodeURIComponent(workspaceId)}&projectId=${encodeURIComponent(projectId)}`});assert.equal(kpis.statusCode,200);assert.ok(Number(kpis.json().kpis.tasks)>=2);const conflict=await app.inject({method:'PUT',url:'/api/development/snapshot',payload:{workspaceId,projectId,sessionId,repository:'owner/shared-app',expectedVersion:99,headCommit:'def'}});assert.equal(conflict.statusCode,409);}finally{await app.close();}});

test('successful development result becomes searchable knowledge',{skip:!db},async()=>{const app=await buildServer();try{const suffix=Date.now().toString(36),workspaceId=`result_e2e_${suffix}`,projectId=`repo-${suffix}`,phrase=`unique token first lesson ${suffix}`;const result=await app.inject({method:'POST',url:'/api/development/results',payload:{workspaceId,projectId,repository:`owner/${projectId}`,commitSha:'abc123',taskType:'optimization',summary:'Token first development result',outcome:'Tests passed',success:true,knowledgeTitle:`Lesson ${suffix}`,knowledgeStatement:phrase,confidence:.8}});assert.equal(result.statusCode,201);assert.ok(result.json().experience?.id);assert.ok(result.json().knowledge?.id);const search=await app.inject({method:'POST',url:'/api/intelligence/search',payload:{workspaceId,projectId,query:phrase,limit:2,minConfidence:.45}});assert.equal(search.statusCode,200);assert.ok(search.json().items.some((x:any)=>x.id===result.json().knowledge.id));}finally{await app.close();}});

test('failed development result is retained but not promoted to knowledge',{skip:!db},async()=>{const app=await buildServer();try{const suffix=Date.now().toString(36),workspaceId=`failed_result_${suffix}`;const result=await app.inject({method:'POST',url:'/api/development/results',payload:{workspaceId,projectId:`repo-${suffix}`,repository:`owner/repo-${suffix}`,summary:'Failed attempt',outcome:'Build failed',success:false,knowledgeTitle:'Should not learn',knowledgeStatement:`do not learn ${suffix}`}});assert.equal(result.statusCode,201);assert.ok(result.json().experience?.id);assert.equal(result.json().knowledge,null);assert.equal(result.json().pattern,null);}finally{await app.close();}});

test('MCP development hub returns compact token-first context',{skip:!db},async()=>{const app=await buildServer();try{const suffix=Date.now().toString(36),workspaceId=`mcp_e2e_${suffix}`;const init=await app.inject({method:'POST',url:'/mcp',payload:{jsonrpc:'2.0',id:1,method:'initialize'}});assert.equal(init.statusCode,200);const opened=await app.inject({method:'POST',url:'/mcp',payload:{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'development_session_open',arguments:{workspaceId,projectId:'shared-app',agentId:'agent-b',clientType:'other-ai',repository:'owner/shared-app',baseCommit:'abc'}}}});assert.equal(opened.statusCode,200);const context=await app.inject({method:'POST',url:'/mcp',payload:{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'development_context_get',arguments:{workspaceId,projectId:'shared-app',query:'typecheck structural failures',limit:3}}}});assert.equal(context.statusCode,200);for(const item of context.json().result.structuredContent.intelligence){assert.deepEqual(Object.keys(item).sort(),['confidence','id','summary','title']);}}finally{await app.close();}});
