import { z } from 'zod';
export const DevelopmentFingerprint=z.object({runtime:z.string().optional(),framework:z.string().optional(),database:z.string().optional(),auth:z.string().optional(),billing:z.string().optional(),environment:z.string().optional(),planModel:z.string().optional(),appRole:z.string().optional(),contractVersion:z.string().optional(),nodeVersion:z.string().optional()});
export const ExperienceInput=z.object({workspaceId:z.string().min(1),projectId:z.string().min(1),appId:z.string().min(1).optional(),componentId:z.string().min(1).optional(),repository:z.string().optional(),branch:z.string().optional(),commitSha:z.string().optional(),taskType:z.string().optional(),summary:z.string().min(1),fingerprint:DevelopmentFingerprint.optional(),context:z.record(z.string(),z.unknown()).default({}),outcome:z.string().optional(),success:z.boolean().optional(),startedAt:z.iso.datetime().optional(),completedAt:z.iso.datetime().optional()});
export const VerificationInput=z.object({checkType:z.string().min(1),status:z.enum(['success','warning','error','skipped']),command:z.string().optional(),durationMs:z.number().int().nonnegative().optional(),evidenceId:z.uuid().optional(),metadata:z.record(z.string(),z.unknown()).default({})});
export const ProductionVerificationMatrix=z.object({productionDeployed:z.boolean().default(false),uiReachable:z.boolean().default(false),permissionVerified:z.boolean().default(false),requiresPersistence:z.boolean().default(false),persistenceVerified:z.boolean().default(false),requiresIntegration:z.boolean().default(false),integrationVerified:z.boolean().default(false),humanVerified:z.boolean().default(false)});
export const EvidenceInput=z.object({kind:z.string().min(1),uri:z.string().optional(),sha256:z.string().optional(),contentExcerpt:z.string().max(12000).optional(),metadata:z.record(z.string(),z.unknown()).default({})});
export const ObservationInput=z.object({workspaceId:z.string().min(1),title:z.string().min(1),statement:z.string().min(1),conditions:z.record(z.string(),z.unknown()).default({}),confidence:z.number().min(0).max(1).default(.5),evidenceIds:z.array(z.uuid()).default([]),metadata:z.record(z.string(),z.unknown()).default({})});
export const RetrievalInput=z.object({workspaceId:z.string().min(1),projectId:z.string().min(1).optional(),loopRunId:z.uuid().optional(),trackUsage:z.boolean().default(false),query:z.string().min(1),queryEmbedding:z.array(z.number().finite()).min(1).max(4096).optional(),embeddingProfileId:z.string().min(1).optional(),kinds:z.array(z.enum(['observation','pattern','rule','skill'])).optional(),minConfidence:z.number().min(0).max(1).default(.35),limit:z.number().int().min(1).max(20).default(8),includeDeprecated:z.boolean().default(false)}).superRefine((x,ctx)=>{if(x.trackUsage&&!x.projectId)ctx.addIssue({code:'custom',message:'projectId is required when trackUsage is true',path:['projectId']});if(x.queryEmbedding&&!x.embeddingProfileId)ctx.addIssue({code:'custom',message:'embeddingProfileId is required when queryEmbedding is provided',path:['embeddingProfileId']});if(x.embeddingProfileId&&!x.queryEmbedding)ctx.addIssue({code:'custom',message:'queryEmbedding is required when embeddingProfileId is provided',path:['queryEmbedding']});});
export function productionUsable(v:z.infer<typeof ProductionVerificationMatrix>){return v.productionDeployed&&v.uiReachable&&v.permissionVerified&&(!v.requiresPersistence||v.persistenceVerified)&&(!v.requiresIntegration||v.integrationVerified);}
export type ExperienceInputType=z.infer<typeof ExperienceInput>;export type VerificationInputType=z.infer<typeof VerificationInput>;export type ProductionVerificationMatrixType=z.infer<typeof ProductionVerificationMatrix>;export type EvidenceInputType=z.infer<typeof EvidenceInput>;export type ObservationInputType=z.infer<typeof ObservationInput>;export type RetrievalInputType=z.infer<typeof RetrievalInput>;
