export type ObservationCandidate={id:string;workspaceId:string;title:string;statement:string;projectId:string;success:boolean;verified:boolean;confidence:number};
export type PatternProposal={title:string;statement:string;observationIds:string[];projectsSeen:number;successCount:number;failureCount:number;verifiedSuccesses:number;confidence:number};
const STEMS:Record<string,string>={fails:'fail',failed:'fail',failure:'fail',failures:'fail',changes:'change',changed:'change',changing:'change',builds:'build',tests:'test',tested:'test',testing:'test',errors:'error'};
function normalizeToken(x:string){return STEMS[x]??(x.length>4&&x.endsWith('s')?x.slice(0,-1):x);}
export function normalizeKnowledgeText(value:string):string{return value.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu,' ').replace(/\s+/g,' ').trim();}
function tokens(value:string){return new Set(normalizeKnowledgeText(value).split(' ').filter(Boolean).map(normalizeToken));}
function jaccard(aa:Set<string>,bb:Set<string>){if(!aa.size||!bb.size)return 0;let intersection=0;for(const x of aa)if(bb.has(x))intersection++;return intersection/(aa.size+bb.size-intersection);}
function ngrams(value:string,size=3){const normalized=normalizeKnowledgeText(value).replace(/\s+/g,'');const out=new Set<string>();if(!normalized)return out;if(normalized.length<=size){out.add(normalized);return out;}for(let i=0;i<=normalized.length-size;i++)out.add(normalized.slice(i,i+size));return out;}
export function tokenSimilarity(a:string,b:string):number{const lexical=jaccard(tokens(a),tokens(b));const character=jaccard(ngrams(a),ngrams(b));return Math.max(lexical,character);}
export function proposePattern(seed:ObservationCandidate,candidates:ObservationCandidate[],threshold=.55):PatternProposal|null{const matches=[seed,...candidates.filter(x=>x.id!==seed.id&&x.workspaceId===seed.workspaceId&&tokenSimilarity(`${seed.title} ${seed.statement}`,`${x.title} ${x.statement}`)>=threshold)];const projects=new Set(matches.map(x=>x.projectId));if(matches.length<2||projects.size<2)return null;const successCount=matches.filter(x=>x.success).length,failureCount=matches.length-successCount,verifiedSuccesses=matches.filter(x=>x.success&&x.verified).length;const confidence=Math.max(0,Math.min(1,Number(((matches.reduce((n,x)=>n+x.confidence,0)/matches.length)*.55+(successCount/matches.length)*.25+Math.min(1,projects.size/3)*.20).toFixed(4))));return{title:seed.title,statement:seed.statement,observationIds:matches.map(x=>x.id),projectsSeen:projects.size,successCount,failureCount,verifiedSuccesses,confidence};}
