import Fastify from 'fastify';import cors from '@fastify/cors';
import{EvidenceInput,ExperienceInput,ObservationInput,RetrievalInput,VerificationInput}from'./domain.js';import{loadConfig}from'./config.js';import{IntelligenceStore}from'./store.js';import{decideLoop,DEFAULT_LOOP_POLICY}from'./loop-controller.js';
export async function buildServer(){const config=loadConfig();const app=Fastify({logger:true});await app.register(cors,{origin:false});const store=config.DATABASE_URL?new IntelligenceStore(config.DATABASE_URL):null;const need=(reply:any)=>{if(!store){reply.code(503).send({error:'DATABASE_NOT_CONFIGURED'});return false;}return true;};
app.get('/health',async()=>({status:'ok'}));app.get('/version',async()=>({name:'external-intelligence-system',version:'0.2.0'}));app.get('/readiness',async(_q,reply)=>{if(!store)return reply.code(503).send({status:'error',databaseConfigured:false});try{const databaseReachable=await store.ping();return{status:databaseReachable?'success':'error',databaseConfigured:true,databaseReachable};}catch{return reply.code(503).send({status:'error',databaseConfigured:true,databaseReachable:false});}});
app.post('/api/experiences',async(req,reply)=>{if(!need(reply))return;const p=ExperienceInput.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_EXPERIENCE',issues:p.error.issues});return reply.code(201).send({experience:await store!.createExperience(p.data)});});
app.get<{Params:{experienceId:string}}>('/api/experiences/:experienceId',async(req,reply)=>{if(!need(reply))return;const x=await store!.getExperience(req.params.experienceId);return x?{experience:x}:reply.code(404).send({error:'EXPERIENCE_NOT_FOUND'});});
app.post<{Params:{experienceId:string}}>('/api/experiences/:experienceId/evidence',async(req,reply)=>{if(!need(reply))return;const p=EvidenceInput.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_EVIDENCE',issues:p.error.issues});return reply.code(201).send({evidence:await store!.addEvidence(req.params.experienceId,p.data)});});
app.post<{Params:{experienceId:string}}>('/api/experiences/:experienceId/verifications',async(req,reply)=>{if(!need(reply))return;const p=VerificationInput.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_VERIFICATION',issues:p.error.issues});return reply.code(201).send({verification:await store!.addVerification(req.params.experienceId,p.data)});});
app.post('/api/observations',async(req,reply)=>{if(!need(reply))return;const p=ObservationInput.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_OBSERVATION',issues:p.error.issues});return reply.code(201).send({observation:await store!.createObservation(p.data)});});
app.post('/api/intelligence/search',async(req,reply)=>{if(!need(reply))return;const p=RetrievalInput.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_RETRIEVAL',issues:p.error.issues});return{items:await store!.retrieve(p.data)};});
app.post('/api/loop/decide',async(req,reply)=>{const b=req.body as any;if(!b?.state||!b?.signal)return reply.code(400).send({error:'INVALID_LOOP_SIGNAL'});return decideLoop(b.state,b.signal,b.policy??DEFAULT_LOOP_POLICY);});
app.addHook('onClose',async()=>{if(store)await store.close();});return app;}
if(import.meta.url===`file://${process.argv[1]}`){const config=loadConfig();const app=await buildServer();await app.listen({host:'0.0.0.0',port:config.PORT});}
